class AppTexts {
  static Map<String, String> fr = {
    "name": "Romain Floriani",
    "job": "Développeur Flutter",
    "description":
        "Développeur Flutter avec plus de ^b13 ans d'expériences^.\nJ'aime transformer des idées en produits concrets, alliant ^b1fluidité^, ^b1design^ et ^b1performance^.\nQue ce soit pour un projet naissant ou pour améliorer une application existante, je mets un point d'honneur à concevoir des ^b1solutions simples et efficaces.^",
    "homeButton": "Accueil",
    "homeTitle": "Portfolio",
    "aboutTitle": "A propos",
    "workflowTitle": "Mon Travail",
    "contactTitle": "Contact",
    "aboutButton": "A propos",
    "workflowButton": "Mon travail",
    "contactButton": "Contact",
    "educationTitle": "Mes études",
    "educationEpitech": "EPITECH",
    "educationEpitechAccronyme":
        "L'école pour l'informatique et les nouvelles technologies",
    "educationEpitechDiploma": "Expert en technologie de l'information",
    "educationEpitechYear": "2018 - 2022",
    "educationEF": "EF Educations",
    "educationEFAccronyme": "Education First",
    "educationEFDiploma": "École de langue Coréenne",
    "educationEFYear": "2023 - 2024",
    "experienceTitle": "Expériences",
    "experienceFMS": "FollowMySport",
    "experienceFMSYear": "Aujourd'hui",
    "experienceFMSPosition": "Développeur Flutter",
    "experienceFE": "Fastlane Educations",
    "experienceFEYear": "14 mois",
    "experienceFEPosition": "Lead tech Flutter",
    "experienceSI": "Symbol-It",
    "experienceSIYear": "6 mois",
    "experienceSIPosition": "Développeur Flutter",
    "experienceGAAPS": "GAAP Solutions",
    "experienceGAAPSYear": "6 mois",
    "experienceGAAPSPosition": "Développeur Flutter",
    "experienceADEO": "ADEO",
    "experienceADEOYear": "3 mois",
    "experienceADEOPosition": "Développeur Flutter",
    "workflowFMSTitle": "FollowMySport",
    "workflowFeaturesTitle": "Fonctionnalités",
    "workflowFMSDescription":
        "FollowMySport est une application de ^b2vrai suivi live en temps réel^ et d'^b2inscription^ aux courses. Elle permet également un ^b2suivi statistique^ des performances du coureur.",
    "workflowFMSFeaturesGeo": "Géolocalisation",
    "workflowFMSFeaturesPayment": "Paiement in-app (stripe)",
    "workflowFeaturesTechnologies": "Technologies",
    "workflowFETitle": "Speechlab",
    "workflowFEDescription":
        "Speechlab, c'est une application mobile qui propose un ^b2parcours complet^, en 10 minutes par jour, pour être à l'aise à l'oral. Qu'il s'agisse de se ^b2préparer^ pour un ^b2entretien professionnel^ ou une ^b2présentation^ en public",
    "workflowFEFeaturesParkour": "Parcours in-app construit dynamiquement",
    "workflowFEFeaturesIA": "Reconnaissance vocale par IA",
    "workflowFEFeaturesDeeplink": "Deeplink",
    "workflowAMTitle": "AlterMobilité",
    "workflowAMDescription":
        "AlterMobilité est une application qui vise à la ^b2reconversion professionnelle^. Elle propose un ^b2service de voiturier^ dans les grandes villes de France",
    "workflowAMFeaturesAppointment": "Prise de rendez-vous",
    "workflowJMRTitle": "JobMatch'R",
    "workflowJMRDescription":
        "JobMatch'r est une application de ^b2mise en relation^ entre chercheur d'emploi et entreprises. Elle vise la ^b2fluidité^ et la ^b2facilité d'emploi^.",
    "workflowJMRFeaturesGesture": "Détection des interactions utilisateurs",
    "socialNetworkTitle": "Réseaux sociaux",
    "socialNetworkLinkedin": "@romain-floriani",
    "socialNetworkGithub": "@maobeuge",
    "socialNetworkMail": "romainflorianipro@gmail.com",
  };
  static Map<String, String> en = {
    "name": "Romain Floriani",
    "job": "Flutter Developer",
    "description":
        "Flutter developer with more than ^b13 years of experience^.\nI love transforming ideas into concrete products, combining ^b1fluidity^, ^b1design^, and ^b1performance^.\nWhether for a new project or improving an existing application, I am committed to creating ^b1simple and efficient solutions.^",
    "homeButton": "Home",
    "aboutButton": "About",
    "homeTitle": "Portfolio",
    "aboutTitle": "About",
    "workflowTitle": "My Work",
    "contactTitle": "Contact",
    "workflowButton": "My Work",
    "contactButton": "Contact",
    "educationTitle": "My Education",
    "educationEpitech": "EPITECH",
    "educationEpitechAccronyme":
        "The School of Computer Science and New Technologies",
    "educationEpitechDiploma": "Expert in Information Technology",
    "educationEpitechYear": "2018 - 2022",
    "educationEF": "EF Education",
    "educationEFAccronyme": "Education First",
    "educationEFDiploma": "Korean Language School",
    "educationEFYear": "2023 - 2024",
    "experienceTitle": "Experiences",
    "experienceFMS": "FollowMySport",
    "experienceFMSYear": "Present",
    "experienceFMSPosition": "Flutter Developer",
    "experienceFE": "Fastlane Educations",
    "experienceFEYear": "14 months",
    "experienceFEPosition": "Flutter Tech Lead",
    "experienceSI": "Symbol-It",
    "experienceSIYear": "6 months",
    "experienceSIPosition": "Flutter Developer",
    "experienceGAAPS": "GAAP Solutions",
    "experienceGAAPSYear": "6 months",
    "experienceGAAPSPosition": "Flutter Developer",
    "experienceADEO": "ADEO",
    "experienceADEOYear": "3 months",
    "experienceADEOPosition": "Flutter Developer",
    "workflowFMSTitle": "FollowMySport",
    "workflowFeaturesTitle": "Features",
    "workflowFMSDescription":
        "FollowMySport is an application for ^b2real-time live tracking^ and ^b2registration^ for races. It also provides a ^b2statistical tracking^ of runner performance.",
    "workflowFMSFeaturesGeo": "Geolocation",
    "workflowFMSFeaturesPayment": "In-app payment (Stripe)",
    "workflowFeaturesTechnologies": "Technologies",
    "workflowFETitle": "Speechlab",
    "workflowFEDescription":
        "Speechlab is a mobile app offering a ^b2complete journey^, with 10 minutes a day, to become comfortable with public speaking. Whether it's to ^b2prepare^ for a ^b2job interview^ or a ^b2public presentation^.",
    "workflowFEFeaturesParkour": "In-app dynamically built journey",
    "workflowFEFeaturesIA": "AI-powered speech recognition",
    "workflowFEFeaturesDeeplink": "Deeplink",
    "workflowAMTitle": "AlterMobilité",
    "workflowAMDescription":
        "AlterMobilité is an application aimed at ^b2career transition^. It offers a ^b2valet service^ in major cities in France.",
    "workflowAMFeaturesAppointment": "Appointment scheduling",
    "workflowJMRTitle": "JobMatch'R",
    "workflowJMRDescription":
        "JobMatch'r is an app that ^b2connects^ job seekers and employers. It aims for ^b2fluidity^ and ^b2ease of use^.",
    "workflowJMRFeaturesGesture": "User interaction detection",
  };
  static Map<String, String> kr = {
    "name": "Romain Floriani",
    "job": "Flutter 개발자",
    "description":
        "^b13년 이상의 경험^을 가진 Flutter 개발자입니다.\n아이디어를 구체적인 제품으로 전환하는 것을 좋아하며, ^b1유연성^, ^b1디자인^, 그리고 ^b1성능^을 결합합니다.\n새로운 프로젝트든 기존 애플리케이션 개선이든, 저는 ^b1간단하고 효율적인 솔루션^을 설계하는 것을 중요하게 생각합니다.",
    "homeButton": "홈",
    "aboutButton": "소개",
    "homeTitle": "포트폴리오",
    "aboutTitle": "소개",
    "workflowTitle": "나의 작업",
    "contactTitle": "연락처",
    "workflowButton": "나의 작업",
    "contactButton": "연락처",
    "educationTitle": "내 학업",
    "educationEpitech": "에피텍",
    "educationEpitechAccronyme": "컴퓨터 과학 및 신기술 학교",
    "educationEpitechDiploma": "정보 기술 전문가",
    "educationEpitechYear": "2018 - 2022",
    "educationEF": "EF 교육",
    "educationEFAccronyme": "Education First",
    "educationEFDiploma": "한국어 어학원",
    "educationEFYear": "2023 - 2024",
    "experienceTitle": "경력",
    "experienceFMS": "FollowMySport",
    "experienceFMSYear": "현재",
    "experienceFMSPosition": "Flutter 개발자",
    "experienceFE": "패스트레인 에듀케이션",
    "experienceFEYear": "14개월",
    "experienceFEPosition": "Flutter 기술 리드",
    "experienceSI": "심볼잇",
    "experienceSIYear": "6개월",
    "experienceSIPosition": "Flutter 개발자",
    "experienceGAAPS": "GAAP 솔루션",
    "experienceGAAPSYear": "6개월",
    "experienceGAAPSPosition": "Flutter 개발자",
    "experienceADEO": "ADEO",
    "experienceADEOYear": "3개월",
    "experienceADEOPosition": "Flutter 개발자",
    "workflowFMSTitle": "FollowMySport",
    "workflowFeaturesTitle": "기능",
    "workflowFMSDescription":
        "FollowMySport는 ^b2실시간 라이브 추적^ 및 경주 ^b2등록^을 위한 애플리케이션입니다. 또한 주자의 성능에 대한 ^b2통계적 추적^을 제공합니다.",
    "workflowFMSFeaturesGeo": "위치 기반 서비스",
    "workflowFMSFeaturesPayment": "인앱 결제 (Stripe)",
    "workflowFeaturesTechnologies": "기술",
    "workflowFETitle": "Speechlab",
    "workflowFEDescription":
        "Speechlab은 매일 10분 동안 ^b2완전한 과정^을 제공하여 말하기에 익숙해지도록 돕는 모바일 앱입니다. ^b2취업 면접^이나 ^b2공개 발표^를 ^b2준비^하는 데 도움을 줍니다.",
    "workflowFEFeaturesParkour": "동적으로 구성된 인앱 여정",
    "workflowFEFeaturesIA": "AI 기반 음성 인식",
    "workflowFEFeaturesDeeplink": "디프 링크",
    "workflowAMTitle": "AlterMobilité",
    "workflowAMDescription":
        "AlterMobilité는 ^b2직업 전환^을 목표로 하는 애플리케이션입니다. 프랑스 주요 도시에서 ^b2발렛 서비스^를 제공합니다.",
    "workflowAMFeaturesAppointment": "예약 일정 관리",
    "workflowJMRTitle": "JobMatch'R",
    "workflowJMRDescription":
        "JobMatch'r는 구직자와 고용주를 ^b2연결^하는 애플리케이션입니다. ^b2유연성^과 ^b2사용 편의성^을 목표로 합니다.",
    "workflowJMRFeaturesGesture": "사용자 상호작용 감지",
  };
}
